### ISSUE TITLE
question about issues !

### ISSUE THREAD

**Issue by grazius** [john-westcott-iv/ansible-tower#10]
Hello
as i see you maintain the jenkinsci/ansible-tower-plugin but the issue tracking is not activated on this repository.

my question is where to post new issues on this plugin ? (issues.jenkins.io, this repository or the jenkinsci/ansible-tower-plugin with issues tracking activated)

Best regards

**Comment by grazius** [comment]
@john-westcott-iv Are you still the official maintainer of this jenkins plugin ?

**Comment by grazius** [comment]
I open [JENKINS-65013](https://issues.jenkins.io/browse/JENKINS-65013) in Jenkins JIRA
If it's the good way to address issues maybe your just need to have a little comment on the plugin homepage ;)

**Comment by john-westcott-iv** [comment]
I am still maintaining this (although there has not been a lot of changes lately). I will take a look at the issue and track it there.
