### ISSUE TITLE
Tower 3.3 no longer supports authtoken for authentication

### ISSUE THREAD

**Issue by fherbert** [john-westcott-iv/ansible-tower#4]
Authtoken support has been removed from awx (and tower from version 3.3) so this plugin no longer authenticates. More info regarding this change is here https://github.com/ansible/awx/blob/devel/docs/auth/session.md

**Comment by unlikelyzero** [comment]
@john-westcott-iv I'd like to help stay in front of this change given tower's upcoming change

Edit: This should now only be an issue for tower-3.4 set to be released in Dec

**Comment by john-westcott-iv** [comment]
@unlikelyzero Do you know of a plugin specifically supporting an OAuthToken? To get the coding started I used [the plain credentials plugin](https://plugins.jenkins.io/plain-credentials) and just made a Secret Text to dump my test token into. Its working but if there is a better plugin for storing OAuth Tokens that you know of we can switch to that.

**Comment by unlikelyzero** [comment]
[I believe this guide helps with best practices surrounding auth tokens.]( https://github.com/jenkinsci/credentials-plugin/blob/master/docs/consumer.adoc)
The **plain credentials plugin** looks fine as far as I can tell, too.
